### ISSUE TITLE
IAM service compatible with AWS

### ISSUE THREAD

**Issue by jonaustin09** [versity/versitygw#140]
**Describe the solution you'd like**
Change the implementation of IAM service to make it more compatible with AWS. 
1. Remove Admin CLI and use aws iam CLI as client side admin CLI.
2. Register proper api handlers for user access creation and deletion.

**Additional context**
Helpfull resources:
[AWS IAM](https://docs.aws.amazon.com/cli/latest/userguide/cli-services-iam-create-creds.html)

**Comment by kfox1111** [comment]
Would this include oidc as well?

**Comment by benmcclelland** [comment]
> Would this include oidc as well?

This issue was tracking the api to manage internal IAM server. And is relatively low priority. We could add support for OIDC as an IAM service though.  This would be good to request in a separate feature request issue.

**Comment by benmcclelland** [comment]
Closing this as unlikely to ever happen.
