### ISSUE TITLE
S3 Proxy GetBucketAcl incorrect result

### ISSUE THREAD

**Issue by jonaustin09** [versity/versitygw#336]
**Describe the bug**
When running `GetBucketAcl_success` integration test, it returns incorrect result.

*Result*
 expected grants to be [{0x1400031e040 FULL_CONTROL {}} {0x1400031e080 READ_ACP {}} {0x1400031e0c0 WRITE {}}], instead got [{0x14000393dc0 FULL_CONTROL {}} {0x140004100c0 READ_ACP {}} {0x140004103c0 WRITE {}}]

**To Reproduce**
```
./versitygw test -a a -s s --endpoint http://localhost:7071 GetBucketAcl_success
```

**Expected behavior**
It has to successfully pass the integration test

**Comment by benmcclelland** [comment]
for this one, I think we need a way to store our own ACLs separately from the backend ACLs. So we dont want to forward the ACL to the backend, we need to encode it in the bucket metadata or something else.
