### ISSUE TITLE
Add object versioning support to frontend

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#417]
**Describe the solution you'd like**
To setup for future use and backends that support versioning, let's add the following API support in the forntend:
[GetBucketVersioning](https://docs.aws.amazon.com/AmazonS3/latest/API/API_GetBucketVersioning.html)
[ListObjectVersions](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectVersions.html)
[PutBucketVersioning](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketVersioning.html)
GetObject: [versionId](https://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html#API_GetObject_RequestSyntax)
And DeleteObject: https://docs.aws.amazon.com/AmazonS3/latest/userguide/DeletingObjectVersions.html

**Additional context**
This feature request is only to add support for the frontend. There is currently no design to be able to add this support in posix backend.

**Comment by jonaustin09** [comment]
done
