### ISSUE TITLE
posix: document all supported S3 API operations in wiki docs

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#42]

**Comment by nzrutman** [comment]
Missing Get/PutObjectAcl; maybe you're just waiting for issue #30

**Comment by benmcclelland** [comment]
> Missing Get/PutObjectAcl; maybe you're just waiting for issue #30

Added to the docs. #30 will initially focus on Bucket ACLs.  If Object ACLs aren’t immediately supported as well, I’ll add a new issue for object ACLs.

**Comment by benmcclelland** [comment]
since docs are in place on the wiki, im going to close this issue for now.  we will just keep the wiki updated with the api progress as we go.
