### ISSUE TITLE
Add keepalive messages for long running commands to prevent client timeouts

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#423]
**Describe the solution you'd like**
Some commands like complete multipart upload can take a long time on some filesystems and possibly timeout on the client side. This causes the clients to have to set long timeouts for these commands to be successful.

We need to investigate if there are messages that can be sent back to the client periodically to let it know that the server is still processing the command.

**Comment by jonaustin09** [comment]
Request timeout is controlled by client side.
In case of aws CLI `--cli-read-timeout` flag is added to the actions(the default value is 60).
In case of aws SDKs:
```
ctx, cancel := context.WithTimeout(context.Background(), <timeout duration here>)
_, err := s3client.PutBucketAcl(ctx, &s3.PutBucketAclInput{
	Bucket: bucket,
})
```
Other SDKs also have their options to control request timeout.
