### ISSUE TITLE
get-bucket-policy command displays non-policy bucket/object info instead

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#433]
**Describe the bug**

When running aws s3api's **get-bucket-policy** query, something similar to the following is returned, with a "Policy" header, but with object info, not policy info:

```
"Policy": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<ListBucketResult xmlns=\"http://s3.amazonaws.com/doc/2006-03-01/\"><Delimiter></Delimiter><EncodingType></EncodingType><IsTruncated>false</IsTruncated><Marker></Marker><MaxKeys>1000</MaxKeys><Name>test-bucket-luke-3</Name><NextMarker></NextMarker><Prefix></Prefix><RequestCharged></RequestCharged><ResultMetadata></ResultMetadata></ListBucketResult>"
```

**To Reproduce**
1.  Run versitygw
2.  Create a bucket, e.g.:
`aws --no-verify-ssl s3 mb test-bucket-luke-3`
3.  Send a get-bucket-policy command to versitygw, e.g.:
`aws --no-verify-ssl s3api get-bucket-policy --bucket test-bucket-luke-3`

**Expected behavior**
The policy info of the bucket is displayed.

**Server Version**
 output of
```
./versitygw -version
uname -a
```
```
Version  : v0.14
Build    : a75112f
BuildTime: 2024-03-01_06:54:22PM
Darwin Lukes-MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:51 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6030 arm64
```

**Additional context**
Describe s3 client and version if applicable.
`aws-cli/2.15.10 Python/3.11.6 Darwin/23.2.0 exe/x86_64 prompt/off`

**Comment by benmcclelland** [comment]
Fixed with #436
