### ISSUE TITLE
put-bucket-policy command creates new bucket instead of changing policy

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#434]
**Describe the bug**
The *put-bucket-policy* command creates a new bucket, and returns an error if the bucket already exists.

Error:
```
An error occurred (BucketAlreadyExists) when calling the PutBucketPolicy operation: The requested bucket name is not available. The bucket name can not be an existing collection, and the bucket namespace is shared by all users of the system. Please select a different name and try again.
```

**To Reproduce**
Steps to reproduce the behavior.

1.  Run versitygw.
2. Create a policy file containing something like the following:
```
{
    "Version": "2024-03-04",
    "Statement": [
        {
            "Principal": {
                "AWS": "arn:aws:iam::<id>:root"
            },
            "Effect": "Allow",
            "Action": "s3:PutBucketPolicy",
            "Resource": "arn:aws:s3:::test-bucket-luke-2"
        }
    ]
}
```
3.  Attempt to put policy with a command like:
`aws --no-verify-ssl s3api put-bucket-policy --bucket test-bucket-luke-3 --policy file:///Users/lukemccrone/devel/versitygw/versity-policy.json`

**Expected behavior**
The policy is added and queryable with the *get-bucket-policy* query.

**Server Version**
 output of
```
./versitygw -version
uname -a
```
```
Version  : v0.14
Build    : a75112f
BuildTime: 2024-03-01_06:54:22PM
Darwin Lukes-MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:54:51 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6030 arm64
```

**Additional context**
`aws-cli/2.15.10 Python/3.11.6 Darwin/23.2.0 exe/x86_64 prompt/off`

**Comment by benmcclelland** [comment]
Fixed with #436
