### ISSUE TITLE
Webhook for notifications

### ISSUE THREAD

**Issue by thenitai** [versity/versitygw#475]
Hi there,

Thank you for this great piece of software. While I see that there is support for Kafka and Nats, I was wondering if a simple webhook would be possible in the future. 

The reason is that both Kafka and Nats require installation, configuration, etc. However, it feels like a total overkill when one wants to know if an upload is done.

Maybe this is just me, but I think it would make a great addition, no? Of course, if there is another option that I'm missing, please let me know.

Thank you for considering.

**Comment by benmcclelland** [comment]
@thenitai I was thinking about this as well when we were first implementing the event system. But I was mainly waiting for someone to ask to make sure there was interest in this. I think we could add this.

**Comment by benmcclelland** [comment]
@thenitai, PR #488 was merged with the webhook events.  See if this looks like it will work for you. We are going to be adding a bit more configuration around what events to send to various event backends in a future PR.

**Comment by thenitai** [comment]
> @thenitai, PR #488 was merged with the webhook events. See if this looks like it will work for you. We are going to be adding a bit more configuration around what events to send to various event backends in a future PR.

First off, thank you for implementing.

I've read the code but honestly not sure how to use it. Would it be the same as the other notification syntaxes, e.g., --event-webhook https://app/event ? I imagine that the most important notification is when a file has finished uploading.

I can test it here, too.

Thank you.

**Comment by benmcclelland** [comment]
> I've read the code but honestly not sure how to use it. Would it be the same as the other notification syntaxes, e.g., --event-webhook https://app/event ? I imagine that the most important notification is when a file has finished uploading.

The option would be `--event-webhook-url <url>`. This will currently send all events, but we have another PR in progress now to add filtering capabilities to events with a similar configuration to aws.

**Comment by benmcclelland** [comment]
New utils command addes to generate a default notification filter, pass in directory to create file. For example:
```
./versitygw utils gen-event-filter-config -p /tmp
```

This will create `/tmp/event_config.json`. Edit this to only true for the events you want to be notified for. Then pass in the options:
```
--event-webhook-url <webhook-url> --event-filter /tmp/event_config.json
```

**Comment by thenitai** [comment]
Awesome. I will give it a go shortly. Thank you so much for making it possible in a short time.
