### ISSUE TITLE
s3cmd produced presigned URLs are not authorized by the gateway

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#478]
**Describe the bug**
The presigned URLs generated by `s3cmd` do not include all of the authorization headers that the gateway is expecting. Since this works with AWS, we should allow authorization with just the headers that `s3cmd` generates. Specifically the `Signature` header.

**To Reproduce**
```
% s3cmd -c s3cfg.local signurl "s3://mybucket/myfile" "$(( $(date +%s) + 900 ))"
http://127.0.0.1:7070/mybucket/myfile?AWSAccessKeyId=test&Expires=1711475575&Signature=VOv3ss2L9VUHgdfBzcvJeGmQKzE%3D
% curl -O 'http://127.0.0.1:7070/mybucket/myfile?AWSAccessKeyId=test&Expires=1711475575&Signature=VOv3ss2L9VUHgdfBzcvJeGmQKzE%3D'
% cat myfile                                                                                                   
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Authorization header is invalid -- one and only one &#39; &#39; (space) required.</Message><Resource></Resource><RequestId></RequestId><HostId></HostId></Error>%                                                                               
```

server:
```
10:38:16 | 400 |     233.167µs | 127.0.0.1 | GET | /mybucket/myfile | -
```
**Expected behavior**
The generated URL should allow downloading of this object

**Additional context**
So far this has only been seen with `s3cmd` generating these URLs. Other clients generate headers that are supported by the gateway.

**Comment by benmcclelland** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-query-string-auth.html describes the required headers. For this case it appears s3cmd is not constructing the URL with all required headers. We can keep this open as a wont fix for now until we find out how prevalent this is to not have expected headers in presign URLs.

**Comment by benmcclelland** [comment]
Closing as a wont fix as this seems to be an issue with s3cmd not following spec.

**Comment by PlkMarudny** [comment]
@aws-sdk/s3-request-presigner^3.750.0 for Node also generates pre-signed urls that gateway rejects, isn't this a gateway problem after all?
