### ISSUE TITLE
Add abstraction layer for object metadata in posix backend

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#511]
This issue started from discussion ideas: #510

Some filesystems (NFSv3 👀) don't support xattrs. So it's disappointing that we cant run the gateway on these due to the xattr requirement for bucket/object metadata storage. Some other techniques for NFS user metadata have been:

* store metadata in sidecar file (so a .meta file for each real file written)
* store metadata in external database or key value store

and there are probably others.

Instead of committing to only one way and annoying everyone who would have preferred it the other way, maybe we can add a metadata storage abstraction in posix and allow the option of adding as many as we need.  We can default to the xattr storage when available, but maybe have sidecar or external storage be options if xattrs are not desired or available.

We probably only need something like this:
```go
// MetadataStorer defines the interface for managing metadata.
type MetadataStorer interface {
    // RetrieveAttribute retrieves the value of a specific attribute for an object in a bucket.
    // Returns the value of the attribute, or an error if the attribute does not exist.
    RetrieveAttribute(bucket, object, attribute string) ([]byte, error)

    // StoreAttribute stores the value of a specific attribute for an object in a bucket.
    // If attribute already exists, new attribute should replace existing.
    // Returns an error if the operation fails.
    StoreAttribute(bucket, object, attribute string, value []byte) error
    
    // DeleteAttribute removes the value of a specific attribute for an object in a bucket.
    // Returns an error if the operation fails.
    DeleteAttribute(bucket, object, attribute string) error
}
```

and then replace all of the xattr calls in posix with this abstracted metadata interface.

This would allow future additions of news ways to store attributes as they come up.

**Comment by benmcclelland** [comment]
I think we will need this as well:
```
    // DeleteAttributes removes all attributes for an object in a bucket.
    // Returns an error if the operation fails.
    DeleteAttributes(bucket, object string) error
```

The xattrs automatically get cleaned up when the file is removed. But this wouldn't be the case for other implementations. So we would need to add specific cleaning when removing objects.

**Comment by scaleoutsean** [comment]
Made use of this with /data on BeeGFS - awesome!
