### ISSUE TITLE
Attempt to put canned bucket ACL of "public-read" results in "Invalid Request"

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#561]
**Describe the bug**
Direct communication with AWS (after enabling ACLs and public access to the bucket) results in the expected behavior, but attempting to put the ACL via versity results in the following being returned:
```
An error occurred (InvalidRequest) when calling the PutBucketAcl operation: Invalid Request
```

**To Reproduce**
1.  Create a bucket in the **Amazon S3** console.
2. Select the bucket and select the **Permissions** tab.
3. Check the **Block public access** section and select **Edit** and set **Block *all* public access** to **off** if not already off.
4. Go to the **Object Ownership** section, select **Edit**, and select **ACLs Enabled** and set **Object Ownership** to **Object Writer** if this hasn't already been done.
5. Set the `AWS_ENDPOINT_URL` value to point to the versity gateway, and send the following command: `aws --no-verify-ssl s3api put-bucket-acl --bucket <name> --acl public-read`

**Expected behavior**
The request succeeds, and the `get-bucket-acl` command returns a **Grants** element similar to the following:
```
{
     "Grantee": {
         "Type": "Group",
         "URI": "http://acs.amazonaws.com/groups/global/AllUsers"
     },
     "Permission": "READ"
 }
```

**Server Version**
```
Version  : v0.21
Build    : 10ed210
BuildTime: 2024-05-02_11:46:50PM
Darwin Lukes-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64
```

**Comment by lrm25** [comment]
More debugging info:  in **s3cmd**, as with **aws**, the setacl command works, but with communication via **versitygw**, the following error is returned:
```
Problem: <class 'AttributeError: 'ConfigParser' object has no attribute 'readfp'
   S3cmd:   2.4.0
   python:   3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
   environment LANG=NOTSET
```

**Comment by jonaustin09** [comment]
Thanks for the bug report, I'll take a look. For your information our implementation of Bucket ACLs differ from traditional AWS ACLs. Some features aren't supported in our end. I'll double check this part.
