### ISSUE TITLE
Regression between 0.20 and 0.21+ with s3fs

### ISSUE THREAD

**Issue by bdwheele** [versity/versitygw#570]
**Describe the bug**
S3FS will no longer connect to versitygw after upgrading to 0.21+, but it (mostly) works on 0.20.  

**To Reproduce**
Start versitygw on a directory with this structure (.txt files are just random text):
```
testbucket/
  hi.txt
  thing/
    hello.txt
testbucket2/
  goodbye.txt
```
using this command:
`versitygw --access xxx --secret xxx posix  ~/test_versity`

For the s3fs side, create the mount directory and start s3fs:
```
mkdir /tmp/s3
echo "xxxx:xxxx" > /tmp/.password_s3fs
s3fs -d -o listobjectsv2 -o del_cache -o complement_stat -o compat_dir -o use_path_request_style -o url=http://localhost:7070/ -o passwd_file=/tmp/.password_s3fs testbucket /tmp/s3
```
When using 0.21+, listing the directory returns an I/O error:
```
$ ls /tmp/s3
ls: cannot access '/tmp/s3': Input/output error
``` 
**Expected behavior**
With 0.20 the above results in the expected behavior:

```
$ ls -al /tmp/s3
total 9
drwx------.  1 bdwheele bdwheele 4096 Dec 31  1969 .
drwxrwxrwt. 26 root     root      660 May 16 14:04 ..
-rw-r-----.  1 bdwheele bdwheele    9 May 16 06:38 hi.txt
-rwxr-x---.  1 bdwheele bdwheele 4096 May 16 06:38 thing

```

**Server Version**
Fedora 40 x86-64
versitygw rpm 0.20, 0.21, and 0.22 from github
s3fs-fuse 1.94 rpm from distro

 
**Additional context**
There's a bug somewhere in 0.20 that confuses s3fs into thinking that directories are actually executable files -- I was attempting to debug the issue when I discovered that I couldn't build the latest source and get it to work at all.

Whatever versitygw is sending back in the more recent version causes s3fs to just stop communicating with the gateway.

**Comment by benmcclelland** [comment]
@bdwheele can you give the errors you are seeing when trying to build the latest version?

**Comment by bdwheele** [comment]
I can build it without issue -- I just get an I/O error when I try to use s3fs to access the gateway.   

It looks like this code in s3api/controllers/base.go:2225 is the culprit:
```
	utils.SetResponseHeaders(ctx, []utils.CustomHeader{		
		{
			Key:   "X-Amz-Access-Point-Alias",
			Value: "false",
		},
		{
			Key:   "X-Amz-Bucket-Region",
			Value: region,
		},
	})
```
Those were added in 0.21 and when I comment them out I get the same (wrong directory) behavior as before rather than the I/O error.  s3fs apparently doesn't like those headers.  I tried each of them independently and if either of them are present I get the I/O error.

**Comment by bdwheele** [comment]
It looks like it's actually a bug in s3fs and I found someone else with the problem.
https://github.com/s3fs-fuse/s3fs-fuse/issues/2439

On the plus side while troubleshooting this I did fix the issue where s3fs wasn't recognizing directories...I'll try to push a PR for it

**Comment by benmcclelland** [comment]
awesome! thank you for the PR, I'll get this merged once the tests pass
