### ISSUE TITLE
Object deletable and overwritable with both retention and legal hold set

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#579]
**Describe the bug**
Either one of these should prevent deletion, but the object is still deletable.

**NOTE:** when testing is directly done against s3, with just the legal hold, the object is deleted, but the bucket is undeletable due to an earlier version being held on the bucket.  Also, I've attempted to reverse the order of the legal hold and retention policy, but that didn't work either.

**To Reproduce**
1. Create a bucket via versitygw with object lock enabled.
2. Get the object lock configuration for the bucket, and verify that it's enabled.
3. Add an object to the bucket.
4. Set the object retention to **GOVERNANCE** and the retention period to tomorrow.
5. Query the retention and verify this is set.
6. Add a legal hold to the object, setting it to **ON**.
7. Query the object legal hold and verify this is set.
8. Attempt to overwrite and/or delete the object.

**Expected behavior**
Deletion is prevented due to the retention policy and legal hold.

**Server Version**
 output of
```
Version  : v0.22
Build    : 0b86684
BuildTime: 2024-05-20_07:06:33PM
Darwin Lukes-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64
```

**Comment by benmcclelland** [comment]
The object lock is currently enforceable only for user accounts. We will be making some changes so that retention and legal hold can be revoked by admin, but must be done before overriding the lock behavior. We can track this effort in a different ticket.
