### ISSUE TITLE
With the posix backend, uploaded parts are left in the ".sgwtmp" directory after CompleteMultipartUpload

### ISSUE THREAD

**Issue by cvubrugier** [versity/versitygw#626]
**Describe the bug**

Hi,

Thank you for creating and maintaining versitygw.
It is very nice and useful!

**To Reproduce**

* Upload a file.
* Go to the root directory of the posix backend.
* Observe that in directory `$bucket/multipart/object/upload-id`, all parts (1, 2, ...) are left.

I identified the root cause and will contribute a fix.

In [CompleteMultipartUpload](https://github.com/versity/versitygw/blob/main/backend/posix/posix.go#L659), the path argument to os.RemoveAll() does not start with the bucket name. Since the path does not exist, [os.RemoveAll()](https://pkg.go.dev/os#RemoveAll) does nothing and uploaded parts are left in the ".sgwtmp" directory.

The issue exists in CompleteMultipartUpload but does _not_ exist in AbortMultipartUpload.

**Expected behavior**

No parts should be left when CompleteMultipartUpload completes.

**Server Version**

```
$ ./versitygw --version
Version  : 1.0.1
Build    : d98ca9b0346d8f097ab42d8832895a248756259a
BuildTime: 2024-06-11T21:29:09Z

$ uname -a
Linux xxx 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux
```

**Additional context**
Reproduced with AWS CLI and Cyberduck
* aws-cli 2.15.42
* Cyberduck 8.9.0

**Comment by benmcclelland** [comment]
Wow, even comes with a fix! thank you!

**Comment by cvubrugier** [comment]
Not removing the uploaded parts also confused ListParts and ListMultipartUploads:
* ListMultipartUploads listed _completed_ multipart uploads in addition to in-progress multipart uploads.
* ListParts listed parts for _completed_ multipart uploads as well.

These issues are fixed now.
