### ISSUE TITLE
Out-of-memory error may occur when large ranges are requested with GetObject (Rclone version < 1.64.0)

### ISSUE THREAD

**Issue by cvubrugier** [versity/versitygw#657]
**Describe the bug**

When reading a very large file (40 GiB; larger than the machine RAM size) with [Rclone](https://github.com/rclone/rclone) (version [1.60.1](https://packages.debian.org/bookworm/rclone) from Debian), I observe that versitygw gets killed by the oom-killer.

Rclone prior to version 1.64 requests very large ranges. When reading a 40 GiB file with Rclone version 1.60.1, I observe that 4 GET requests are sent with 10 GiB ranges:

* Range: bytes=0-10737418239
* Range: bytes=10737418240-21474836479
* Range: bytes=21474836480-32212254719
* Range: bytes=32212254720-42949672959

These very large ranges cause versitygw to allocate a large amount of memory to serve these chunks.

I tested with several versions of Rclone. Since version 1.64.0, Rclone requests much smaller chunks (64 MiB) and this issue does not occur.

**To Reproduce**
* Serve files with versitygw 1.0.1 (I use the posix backend)
* Download a very large file with Rclone (version < 1.64.0; for instance version 1.60.1 from Debian 12 bookworm)
* Observe that versitygw gets oom-killed because it consumes too much memory.

**Expected behavior**

Requesting a very large range from a very large file with `GetObject` should not crash versitygw.

**Server Version**

```
$ ./versitygw --version
Version  : 1.0.1
Build    : d98ca9b0346d8f097ab42d8832895a248756259a
BuildTime: 2024-06-11T21:29:09Z

$ uname -a
Linux xxx 6.1.0-21-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.90-1 (2024-05-03) x86_64 GNU/Linux

$ rclone --version
rclone v1.60.1-DEV
- os/version: debian 12.5 (64 bit)
- os/kernel: 6.1.0-21-amd64 (x86_64)
- os/type: linux
- os/arch: amd64
- go/version: go1.19.8
- go/linking: dynamic
- go/tags: none
```

**Additional context**

This bug occurs with Rclone version < 1.64.0. Since version 1.64.0, Rclone requests much smaller chunks (64 MiB) and this issue does not occur.

**Comment by benmcclelland** [comment]
We changed the upload paths to a streaming model to conserve memory. We can look into if it's possible to do the same on the download side to address excessive memory use for large downloads.

**Comment by cvubrugier** [comment]
Thank you @jonaustin09 ans @benmcclelland!
