### ISSUE TITLE
[Bug] - Healthcheck returns HTTP/1.1 400 Bad Request

### ISSUE THREAD

**Issue by dmcp718** [versity/versitygw#717]
**Describe the bug**
Installed binary from https://github.com/versity/versitygw/releases/download/v1.0.4/versitygw_1.0.4_linux_amd64.deb
lsb_release -a

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

With basic start options 'versitygw posix <path> --health /health', GET returns 400

curl -i http://127.0.0.1:7070/health
HTTP/1.1 400 Bad Request
Server: VERSITYGW
Date: Tue, 06 Aug 2024 13:14:18 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 243
Connection: close

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidArgument</Code><Message>Authorization header is invalid -- one and only one &#39; &#39; (space) required.</Message><Resource></Resource><RequestId></Req

**To Reproduce**
Start binary with 'versitygw posix <path> --health /health'
Issue 'curl -i http://127.0.0.1:7070/health'

**Expected behavior**
curl -i http://127.0.0.1:7070/health
OK

**Server Version**
versitygw -v
Version  : 1.0.4
Build    : 733b6e7b2fd686a23d98ef82f3234a37a7cc2dbb
BuildTime: 2024-07-17T15:56:00Z

**Additional context**
<!-- Describe s3 client and version if applicable.

**Comment by benmcclelland** [comment]
The --health is a global option, so needs to be specified before the 'posix', for example:
```
versitygw --health /health posix ...
```

Just tested this over here:
```
% ./versitygw --access test --secret test --health /health posix /tmp/gw
```
```
% curl -i http://127.0.0.1:7070/health
HTTP/1.1 200 OK
Server: VERSITYGW
Date: Tue, 06 Aug 2024 17:14:35 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 2
Connection: close

OK%                                                                             
```

**Comment by dmcp718** [comment]
Thanks for the explanation, confirmed on my end as well.
