### ISSUE TITLE
Dockerfile_test_bats not working

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#722]
**Describe the bug**
This docker image was put in to allow users to test w/o leaving a footprint on their device, and to allow for an easy test run locally.  However, with the move more towards github-actions, it hasn't been updated recently.

**To Reproduce**
1. Build with `docker build --progress=plain -f Dockerfile_test_bats -t <tag name> .`
2. Attempt to run with `docker run <tag name>`

**Expected behavior**
Docker container runs and completes tests.

**Server Version**
Version  : v1.0.4
Build    : ab64441
BuildTime: 2024-08-05_10:56:45PM
Darwin Lukes-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64

**Comment by benmcclelland** [comment]
recent fixes have this working now
