### ISSUE TITLE
[Feature] - Add POSIX UID and GID attribute mapping to LDAP

### ISSUE THREAD

**Issue by nathanschumann** [versity/versitygw#733]
**Describe the solution you'd like**

Vault, S3, and POSIX IAM service backends all support setting a POSIX UID and/or GID for uploaded objects. There does not appear to be a corresponding attribute mapping in LDAP. There should be `VGW_IAM_LDAP_UID_ATTR` and `VGW_IAM_LDAP_GID_ATTR` attribute variables.

**Additional context**

**Comment by benmcclelland** [comment]
I believe these are already there:

```
--iam-ldap-user-id-atr
VGW_IAM_LDAP_USER_ID_ATR
```
```
--iam-ldap-group-id-atr
VGW_IAM_LDAP_GROUP_ID_ATR
```

are these what you are looking for?

**Comment by nathanschumann** [comment]
They need to be added into the `example.conf` file. Here's what's there currently from master/main:

```
#VGW_IAM_LDAP_URL=
#VGW_IAM_LDAP_BASE_DN=
#VGW_IAM_LDAP_BIND_DN=
#VGW_IAM_LDAP_BIND_PASS=
#VGW_IAM_LDAP_QUERY_BASE=
#VGW_IAM_LDAP_OBJECT_CLASSES=
#VGW_IAM_LDAP_ACCESS_ATR=
#VGW_IAM_LDAP_SECRET_ATR=
#VGW_IAM_LDAP_ROLE_ATR=
```

That's why I thought the params didn't exist. I don't look at the switches since users are going to use the conf files.
