### ISSUE TITLE
Internal error when replacing metadata

### ISSUE THREAD

**Issue by tonyipm** [versity/versitygw#734]
**Describe the bug**
Server Internal Error. 
Upload a file object with metadata. Use the copy-object api to copy the file over itself with new metadata. In aws s3 the object exists with new metadata. With Versity Gateway we get an internal error returned.

**To Reproduce**

DEV03 [/WS/WORK] :>echo TEST>testfile
DEV03 [/WS/WORK] :>vgaws s3api put-object --bucket tonyitest --key testfile --metadata abc=123 --body testfile  
{  
   "ETag": "2debfdcf79f03e4a65a667d21ef9de14"  
} 
 
DEV03 [/WS/WORK] :>vgaws s3api head-object --bucket tonyitest --key testfile |grep -A2 Metadata  
   "Metadata": {  
       "abc": "123"  
   }, 

DEV03 [/WS/WORK] :> vgaws s3api copy-object --bucket tonyitest --copy-source tonyitest/testfile --key testfile  --metadata abc=456 --metadata-directive REPLACE 

An error occurred (InternalError) when calling the CopyObject operation (reached max retries: 4): We encountered an internal error, please try again.

Using AWS the operation is successful:

DEV03 [/WS/WORK] :>aws s3api put-object --bucket tonyitest –-key testfile --metadata abc=123 --body testfile   
{  
   "ETag": "\"2debfdcf79f03e4a65a667d21ef9de14\"",  
   "ServerSideEncryption": "AES256"  
}  
  
DEV03 [/WS/WORK] :>aws s3api head-object --bucket tonyitest --key testfile |grep -A2 Metadata   
   "Metadata": {  
       "abc": "123"  
   }  

DEV03 [/WS/WORK] :> aws s3api copy-object --bucket tonyitest --copy-source tonyitest/testfile --key testfile  --metadata 
abc=456 --metadata-directive REPLACE   
{  
   "ServerSideEncryption": "AES256",  
   "CopyObjectResult": {  
       "ETag": "\"2debfdcf79f03e4a65a667d21ef9de14\"",  
       "LastModified": "2024-08-13T14:39:04.000Z"  
   }  
} 
  
DEV03 [/WS/WORK] :>aws s3api head-object --bucket tonyitest --key testfile |grep -A2 Metadata  
   "Metadata": {  
       "abc": "456"  
   } 

**Expected behavior**
Object metadata updated, no Internal Error

**Server Version**
Version  : 
Build    : release-rpm
BuildTime: 2024-08-12_08:42:26AM

Linux ip-10-100-0-246 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Thu Feb 1 03:51:05 EST 2024 x86_64 x86_64 x86_64 GNU/Linux

**Additional context**
n/a

**Comment by benmcclelland** [comment]
I'm adding a bit more to this fix as well. We were previously looking to see if the incoming metadata differed from the source, and sending back an error if not. After some testing with AWS, it looks like we should only be looking at the metadata-directive value being REPLACE or COPY(default). If REPLACE, then we always write the incoming metadata, even if its the same as what already exists.
