### ISSUE TITLE
[Bug] - "The requested URI does not represent any resource on the server" when using root credentials to PutObject with Azure backend

### ISSUE THREAD

**Issue by kamilzzz** [versity/versitygw#736]
**Describe the bug**
PutObject request fails with "The requested URI does not represent any resource on the server" even when using root access.

**To Reproduce**
1. Start gateway with azure backend:
 `docker run -p 7070:7070 versity/versitygw --access s3a --secret s3s azure -a <az-account-name> -k <az-account-key>`
3. Create blob container on Azure Blob Storage manually
4. Export root credentials as env:
```
export AWS_ACCESS_KEY_ID=s3a
export AWS_SECRET_ACCESS_KEY=s3s
```
5. Verify gateway is successfully connecting to storage:
`aws --endpoint-url http://127.0.0.1:7070 s3 ls s3://`. 
Container(s) are listed successfully
7. Try to upload object: 
`aws --endpoint-url http://127.0.0.1:7070 s3 cp localfile s3://<container-from-output-above>/test.txt`
8. Request fails with 400 with following response body - `<Error><Code>InvalidUri</Code><Message>400 The requested URI does not represent any resource on the server.</Message><Resource></Resource><RequestId></RequestId><HostId></HostId></Error>`

**Expected behavior**
Object to be successfully uploaded

**Server Version**
```
Version  : v1.0.5
Build    : adbc8140ed85e6b5b240600b49fcd60fe2282307
BuildTime: 2024-08-06T17:53:24Z
```

**Additional context**
<!-- Describe s3 client and version if applicable.

**Comment by benmcclelland** [comment]
I ran a test against the dev azurite docker container (`make up-azurite`), and this looks ok:
```
% aws s3 mb s3://testbucket
make_bucket: testbucket
% aws s3 ls s3://testbucket
% aws s3 ls                
2024-08-13 17:10:59 testbucket
% echo TEST >localfile
% aws --endpoint-url http://127.0.0.1:7070 s3 cp localfile s3://testbucket/test.txt
upload: ./localfile to s3://testbucket/test.txt  
% aws s3 ls s3://testbucket
2024-08-13 17:12:12          5 test.txt              
```

gateway logs:
```
azuritegw-1  | 2024/08/14 00:10:59 stdout: 00:10:58 | 200 |   81.931417ms | 192.168.65.1 | PUT | /testbucket | - | 
azuritegw-1  | 2024/08/14 00:11:10 stdout: 00:11:10 | 200 |   12.497416ms | 192.168.65.1 | GET | /testbucket | - | list-type=2&prefix=&delimiter=%2F&encoding-type=url
azuritegw-1  | 2024/08/14 00:11:18 stdout: 00:11:17 | 200 |   10.526709ms | 192.168.65.1 | GET | / | - | 
azuritegw-1  | 2024/08/14 00:12:12 stdout: 00:12:11 | 200 |   51.884834ms | 192.168.65.1 | PUT | /testbucket/test.txt | - | 
azuritegw-1  | 2024/08/14 00:13:41 stdout: 00:13:41 | 200 |   35.754875ms | 192.168.65.1 | GET | /testbucket | - | list-type=2&prefix=&delimiter=%2F&encoding-type=url
```

azurite logs:
```
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:10:59 +0000] "PUT /devstoreaccount1/testbucket?restype=container HTTP/1.1" 201 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:11:10 +0000] "GET /devstoreaccount1/testbucket?restype=container HTTP/1.1" 200 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:11:10 +0000] "GET /devstoreaccount1/testbucket?comp=list&marker=&maxresults=1000&prefix=&restype=container HTTP/1.1" 200 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:11:18 +0000] "GET /devstoreaccount1?comp=list&include=metadata HTTP/1.1" 200 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:12:12 +0000] "GET /devstoreaccount1/testbucket?restype=container HTTP/1.1" 200 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:12:12 +0000] "GET /devstoreaccount1/testbucket?restype=container HTTP/1.1" 200 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:12:12 +0000] "PUT /devstoreaccount1/testbucket/test.txt HTTP/1.1" 201 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:13:41 +0000] "GET /devstoreaccount1/testbucket?restype=container HTTP/1.1" 200 -
azurite-1    | 172.20.0.2 - - [14/Aug/2024:00:13:41 +0000] "GET /devstoreaccount1/testbucket?comp=list&marker=&maxresults=1000&prefix=&restype=container HTTP/1.1" 200 -
```

Looks like we will need to setup a real azure account to see if there is any reason any of this would be different from azurite.

**Comment by benmcclelland** [comment]
@kamilzzz  If the `--url` option is not specified for the azure backend, then we will use `https://<account>.blob.core.windows.net/`.  Can you double check that this is the correct URL to access your storage account?

**Comment by kamilzzz** [comment]
That URL is correct as I can correctly list and create buckets.

It still fails when creating to upload object.
Not sure request is even passed to Azure Storage as on the Azure Storage Account level I cannot see any request related to PutObject call. All I can see is listing buckets (containers) and creating one.
Maybe the error comes from the gateway itself and not from Azure storage?

Is there anything specific required to use root access when I specified `--access` and `--secret` global options when starting gateway?

**Comment by benmcclelland** [comment]
> That URL is correct as I can correctly list and create buckets.
> 
> It still fails when trying to upload object. Not sure request is even passed to Azure Storage as on the Azure Storage Account level I cannot see any request related to PutObject call. All I can see is listing buckets (containers) and creating one. Maybe the error comes from the gateway itself and not from Azure storage?
> 
> Is there anything specific required to use root access when I specified `--access` and `--secret` global options when starting gateway?

This error: `The requested URI does not represent any resource on the server.` comes from Azure. The gateway doesn't have any error that matches this string. This also means that your gateway access credentials are good since it's getting to the point of trying to access Azure. I will work on setting up my Azure account again to see if there is any difference between azurite and the real blob storage.

**Comment by benmcclelland** [comment]
Oh yes, I can reproduce this as well. I think you are right, this request doesn't appear to be hitting the Azure backend. This seems to be an issue with the request router possibly. Still looking into this.

**Comment by benmcclelland** [comment]
I merged the PR that should fix the "The requested URI does not represent any resource on the server" error. But this backend is still a bit experimental. Its passing the majority of tests, but the multipart upload is handled differently in azure blob. There is no corresponding create multipart upload, instead azure blob just starts uploading parts and then finalizes them in the complete multipart upload call. So multipart uploads are somewhat functional, but there are some issues with simultaneous multipart uploads of the same object, setting metadata on multipart upload, etc that still needs to be addressed for full functionality.
