### ISSUE TITLE
strange behaviour with directory objects

### ISSUE THREAD

**Issue by tonyipm** [versity/versitygw#740]
**Describe the bug**
Trying to put objects ending in slash into versity s3 yields odd behaviour

**To Reproduce**
Firstly, using aws as reference:

aws s3api put-object --bucket tonyitest --key a/
{
    "ETag": "\"d41d8cd98f00b204e9800998ecf8427e\"",
    "ServerSideEncryption": "AES256"
}
DEV03 [/WS/1061/TI] :>aws s3 ls tonyitest/a/
2024-08-19 16:12:59          0 
DEV03 [/WS/1061/TI] :>aws s3 ls tonyitest/a
                           PRE a/
DEV03 [/WS/1061/TI] :>aws s3 rm s3://tonyitest --recursive
delete: s3://tonyitest/a/

now using verstity s3:

DEV03 [/WS/1061/TI] :>vgaws s3api put-object --bucket tonyitest --key a/
{
    "ETag": "d41d8cd98f00b204e9800998ecf8427e"
}
DEV03 [/WS/1061/TI] :>vgaws s3 ls tonyitest/a/

'Size'
DEV03 [/WS/1061/TI] :>vgaws s3 ls tonyitest/a

'Size'
DEV03 [/WS/1061/TI] :>vgaws s3 rm s3://tonyitest --recursive
fatal error: 'Size'
DEV03 [/WS/1061/TI] :>

**Expected behavior**
Versity should ideally give the exact same behaviour as aws s3 above.

**Server Version**

DEV03 [/WS/VGW.14.08.24/versitygw-main] :>./versitygw --version
Version  : 
Build    : release-rpm
BuildTime: 2024-08-14_09:28:07AM

DEV03 [/WS/VGW.14.08.24/versitygw-main] :>uname -a
Linux ip-10-100-0-246 4.18.0-513.18.1.el8_9.x86_64 #1 SMP Thu Feb 1 03:51:05 EST 2024 x86_64 x86_64 x86_64 GNU/Linux
DEV03 [/WS/VGW.14.08.24/versitygw-main] :>

**Additional context**
<!-- Describe s3 client and version if applicable.

**Comment by benmcclelland** [comment]
Than you for the reproducer. I think the list objects is not handling the single directory case correctly here. I'll add this test to the unit tests and get it addressed.

**Comment by lrm25** [comment]
After reproducing this, I found that this doesn't happen if **s3** is used to put the file into the bucket, rather than **s3api**.  When **s3** is used, the results are identical with direct to s3.
