### ISSUE TITLE
response differs from aws s3

### ISSUE THREAD

**Issue by tonyipm** [versity/versitygw#755]
**Describe the bug**
If an s3 rm command is issued for an object with a name longer than 256 characters, AWS s3 responds with HTTP 2xx status code indicating success even though the object name is illegal. With Versity we get an HTTP 500 Internal Server Error which triggers a retry in the AWS cli. Although it might seem silly that such an object could not exist in the first place, we would like to see the same behaviour between Versity and AWS s3. 

**To Reproduce**
aws s3 rm s3:/bucket/[ any name with >256 characters]

**Expected behavior**
Return value should be the same as aws s3.

**Server Version**
Version  : 
Build    : release-rpm
BuildTime: 2024-08-23_03:04:17PM

**Additional context**

**Comment by benmcclelland** [comment]
Thanks for the steps here. Looks like the PUT side of the long pathname is broken too 😞. I'll see if we need a separate ticket for that or if we can just address both in the same PR.
