### ISSUE TITLE
list-objects in REST returns list-buckets reply

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#788]
**Describe the bug**
Direct to s3, REST `list-objects` commands return a reply in the following format:
```
<?xml version="1.0" encoding="UTF-8"?>
<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>{bucket name}</Name><Prefix></Prefix><Marker></Marker><MaxKeys>1000</MaxKeys><IsTruncated>false</IsTruncated><Contents><Key>test_file</Key><LastModified>2024-09-06T16:16:10.000Z</LastModified><ETag>&quot;b1d046bfa87363856e8b5bf987a6cabf&quot;</ETag><Size>10</Size><Owner><ID>{canonical ID}</ID><DisplayName>{AWS display name}</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>
```

Via versitygw, something similar to the following is returned instead:
```
<?xml version="1.0" encoding="UTF-8"?>
<ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>{key ID}</ID><DisplayName></DisplayName></Owner><Buckets><Bucket><Name>versity-gwtest-bucket-one</Name><CreationDate>2024-09-06T13:15:11.9262355-03:00</CreationDate></Bucket><Bucket><Name>versity-gwtest-userplus-bucket</Name><CreationDate>2024-09-04T13:29:48.504560459-03:00</CreationDate></Bucket></Buckets></ListAllMyBucketsResult>
```

This is the expected `list-buckets` reply.

**To Reproduce**
Run the script at https://github.com/versity/versitygw/wiki/Running-Test-Suite#rest, but replace the list-buckets URL (localhost:7070) with the bucket URL ({bucket name}.localhost:7070 to turn it into a list-objects command.

**Expected behavior**
Like direct to S3, a **ListBucketResult** XML message is returned rather than a **ListAllMyBucketsResult** XML message containing a single bucket.

**Server Version**
Version  : v1.0.6
Build    : 7e30e63
BuildTime: 2024-09-06_10:20:00PM
Darwin Lukes-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64

**Comment by benmcclelland** [comment]
If I run with aws cli, it seems to have the `ListBucketResult` as expected:
```
% aws --debug s3api list-objects --bucket test 2>&1 | grep "^b'"
b'<?xml version="1.0" encoding="UTF-8"?>\n<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Name>test</Name><Prefix></Prefix><Marker></Marker><NextMarker></NextMarker><MaxKeys>1000</MaxKeys><Delimiter></Delimiter><IsTruncated>false</IsTruncated><Contents><LastModified>2024-09-06T15:50:30.415Z</LastModified><ETag>5843979fc12b3ee91ce87763332b9afc</ETag><Key>test</Key><Size>587</Size><StorageClass>STANDARD</StorageClass></Contents><EncodingType></EncodingType></ListBucketResult>'
```
The `ListAllMyBucketsResult` comes from listing buckets instead of listing objects. Could the request you are sending somehow being interpreted as a list buckets instead?

**Comment by lrm25** [comment]
Is there a way to see the underlying REST command when running it from the command line?  It might be a bit different.

**Comment by lrm25** [comment]
OK, I checked the debug output and noticed a difference.  When I send the REST commands, I'm using:
```
GET
/

host:{bucket name}.127.0.0.1:7070
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20240908T000841Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

The format s3api uses is:
```
GET
/versity-gwtest-userplus-bucket
encoding-type=url
host:127.0.0.1:7070
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20240908T000841Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

It looks like direct S3 properly handes my format, but versity does not.

**Comment by benmcclelland** [comment]
Ah, yeah I dont know that we can handle virtual host style bucket access. This access assumes path style.  We may need to add a feature issue for virtual host style access if we want to add this.

**Comment by benmcclelland** [comment]
Closing this and tracking the virtual host addressing feature enhancement in #803
