### ISSUE TITLE
[Bug] - REST responses return empty tags

### ISSUE THREAD

**Issue by lrm25** [versity/versitygw#850]
**Describe the bug**
REST responses directly from s3 do not return empty tags, but REST responses from versitygw do.  While not a serious issue, optional XML tags that aren't set shouldn't be returned.

For example, versitygw returns this when there is no object lock config rule:
```
<?xml version="1.0" encoding="UTF-8"?>
<ObjectLockConfiguration><ObjectLockEnabled>Enabled</ObjectLockEnabled><Rule></Rule></ObjectLockConfiguration>
```

s3 returns this:
```
<?xml version="1.0" encoding="UTF-8"?>
<ObjectLockConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><ObjectLockEnabled>Enabled</ObjectLockEnabled></ObjectLockConfiguration>
```

Since `Rule` is an optional parameter and isn't set.

**To Reproduce**
1.  Send a "GET" rest command, e.g. versioning:  https://github.com/versity/versitygw/blob/test_cmdline_rest_retention/tests/rest_scripts/get_bucket_versioning.sh
2. Send for both direct (s3.amazonaws.com) and versitygw.
3. Compare the two.  Note the empty tags after sending to versitygw.

**Expected behavior**
versitygw doesn't return unnecessary optional XML tags.

**Server Version**
Version  : v1.0.7
Build    : b7291c3
BuildTime: 2024-09-25_08:28:23PM
Darwin Lukes-MacBook-Pro.local 23.4.0 Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:25 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6030 arm64

**Comment by jonaustin09** [comment]
This issue has been fixed in [this](https://github.com/versity/versitygw/pull/849) PR
