### ISSUE TITLE
[Feature] - Make directory umask configurable

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#878]
**Describe the solution you'd like**
When making new directories, we are hard coding the umask to 0755:
https://github.com/versity/versitygw/blob/d2b0d24520fd899525d1f3ff0831d5099262248f/backend/posix/posix.go#L274-L277

Need an option to posix to make this configurable.

**Comment by rstanonik** [comment]
And the file default perms?  Current default seems to be 644, but 664 is needed for sharing within a group.
Thanks,
Ron
