### ISSUE TITLE
gateway metrics

### ISSUE THREAD

**Issue by benmcclelland** [versity/versitygw#88]
This issue is just to capture the feature for general metrics.  This should be something that can track request rates, throughput, etc.  At a minimum we should allow configuring a statsd endpoint, but like everything else we may want to allow configuration of different types of metrics endpoints.

**Comment by mateuszdrab** [comment]
Hey @benmcclelland 

There seems to be no metrics support from native Prometheus format.

Do you mind elaborating why you closed this as complete?
