### ISSUE TITLE
[Bug] - os.PathSeparator incorrect for io/fs

### ISSUE THREAD

**Issue by lunixbochs** [versity/versitygw#903]
**Describe the bug**
[backend.Walk](https://github.com/versity/versitygw/blob/main/backend/walk.go#L88) constructs paths using `os.PathSeparator`

This has two problems:

1. io/fs uses forward slash on all platforms, [including windows](https://pkg.go.dev/io/fs#ValidPath) "Note that paths are slash-separated on all systems, even Windows", so `os.PathSeparator` is incorrect for the io/fs abstraction.
2. The prefix passed in by the caller probably wants to work with either `/` or delimiter, not `os.PathSeparator`

I'm looking at speeding up `backend.Walk`. I'll see about improving this while I'm in there.

**Comment by benmcclelland** [comment]
@lunixbochs Thanks for taking a look at this. I think you are probably right, not much thought was put into using `os.PathSeparator` here.

One optimization that I was trying to figure out if it would be possible is somehow storing the directory and readdir position in the continuation marker. Ideally we would like to continue the walk without having to visit all the previous entries.  The current walk really restricts the bucket scalability to be able to support large bucket list-objects.
