### ISSUE TITLE
[Bug] - HTTP500 from HEAD /bucket/file_not_dir/no_such_file

### ISSUE THREAD

**Issue by Ostheer** [versity/versitygw#942]
**Describe the bug**
Doing a HTTP/HEAD request to a path like  `whatever/this_is_an_existing_file_and_not_a_dir/this_file_cannot_be_here` yields a 500 server error, throwing off some clients expecting a 404 (see context below).
This is what's happening:
```bash
% touch dinges
% stat dinges/whatever
stat: cannot statx 'dinges/whatever': Not a directory
```

Example traffic:
```
HEAD /testbucket/empty-1/.zgroup/.zarray HTTP/1.1
Host: <server hostname>
User-Agent: aiobotocore/2.12.3 md/Botocore#1.34.69 ua/2.0 os/linux#6.6.59-1-lts md/arch#x86_64 lang/python#3.12.7 md/pyimpl#CPython cfg/retry-mode#legacy botocore/1.34.69
X-Amz-Date: 20241107T163316Z
X-Amz-Content-SHA256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
Authorization: AWS4-HMAC-SHA256 Credential=root/20241107/ein-gstl-1/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=35116294580b5e1295e209893a3a6855d16dc71dd763e13e164eb7091b260a1a
amz-sdk-invocation-id: 6e73281f-d345-4220-8729-60e04bcd9de5
amz-sdk-request: ttl=20241107T163329Z; attempt=5; max=5
Accept-Encoding: identity
Accept: */*

HTTP/1.1 500 Internal Server Error
Server: VERSITYGW
Date: Thu, 07 Nov 2024 16:33:16 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 211
Connection: close
```

**To Reproduce**
```python
xr.DataArray().to_zarr("s3://testbucket/empty-0", storage_options={"key": ..., "secret": ..., "endpoint_url": "http://..../"})
```

**Expected behavior**
A 404 would seem sensible.

**Server Version**
```
Version  : 1.0.8
Build    : 45ad3843ef6ee8a325524852e36ed48e45a48721
BuildTime: 2024-10-28T15:42:50Z
```

```
Linux sr-storage 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 GNU/Linux
```

**Additional context**
I am  using Xarray/Zarr to save arrays to S3. I've done this with Minio in the past and this ran fine without any specific configuration. I'm trying to move to VersityGW.
When I try to save the xarray/zarr array to versity-s3, the VersityGW server received some HEAD requests from the xarray/zarr/s3fs/boto stack that presumably probe the existence of a file `/testbucket/empty-0/.zattrs/.zarray`. 
However, `.zattrs` is a file (and not a directory), and VersityGW responds `Internal Error, stat object: stat testbucket/empty-0/.zattrs/.zarray: not a directory`.
These requests are retried after a delay, causing a big slowdown in the process.

**Comment by benmcclelland** [comment]
Yes, I agree that a 404 not found would be more appropriate for this case

**Comment by Ostheer** [comment]
In case anyone else is having this issue, for the time being, a dirty workaround could be adding this to your nginx reverse proxy location block:
```
proxy_intercept_errors on;
error_page 500 = 404;
```

(In addition to 
```
proxy_hide_header X-Amz-Bucket-Region;
proxy_hide_header X-Amz-Access-Point-Alias;
```
which i had to add to get s3fs-fuse to work with VersityGW)

**Comment by Ostheer** [comment]
Thanks for the quick action!

I just recompiled the current git main branch (on a vanilla Debian Bookworm + Go 1.23 from Debian Sid).
After removing the proxy hack I'm still experiencing the same issue (HTTP 500 for `not_a_dir/something` requests), but now with a different internal server error:

New:
`Internal Error, walk testbucket: stat empty-0/.zattrs/.zarray: not a directory`
Old:
`Internal Error, stat object: stat testbucket/empty-0/.zattrs/.zarray: not a directory`

Any ideas?
