### ISSUE TITLE
[Bug] - HTTP500 from GET list /bucket/file_not_dir/no_such_file

### ISSUE THREAD

**Issue by Ostheer** [versity/versitygw#949]
**Describe the bug**
Doing a HTTP/~~HEAD~~ GET request to a path like  `whatever/this_is_an_existing_file_and_not_a_dir/this_file_cannot_be_here` yields a 500 server error, throwing off some clients expecting a 404 (see context below).

In my versity log, I see
` Internal Error, walk testbucket: stat empty-0/.zattrs/.zarray: not a directory`

Note that I previously filed an issue, #942, for this. @benmcclelland quickly merged some changes that slightly but not qualitatively altered the server error message.
I created this second issue because I got no response yet on my comment on the old issue. Feel free to close this and continue work in the old issue.

**To Reproduce**
```python
xr.DataArray().to_zarr("s3://testbucket/empty-0", storage_options={"key": ..., "secret": ..., "endpoint_url": "http://..../"})
```

**Expected behavior**
A 404 would seem sensible.

**Server Version**
Compiled from git master branch after commit 0312a1e3dc3b1085a882d637beecf3cbd5f03f1c as described [in this comment](https://github.com/versity/versitygw/issues/942#issuecomment-2470451252)
```
Version  : 1.0.8
Build    : a26f069
BuildTime: 2024-11-12_01:04:10PM
```

```
Linux sr-storage 6.8.4-2-pve #1 SMP PREEMPT_DYNAMIC PMX 6.8.4-2 (2024-04-10T17:36Z) x86_64 GNU/Linux
```

**Comment by benmcclelland** [comment]
Sorry I missed the update to the other issue. I am able to reproduce this in the list-objects API. Let's keep this issue open for tracking this one since it is slightly different than the other issue (list vs head).

```
% aws s3api put-object --bucket test --key file                      
{
    "ETag": "d41d8cd98f00b204e9800998ecf8427e"
}
% aws s3api list-objects-v2 --bucket test --prefix file/file/file

An error occurred (InternalError) when calling the ListObjectsV2 operation (reached max retries: 2): We encountered an internal error, please try again.
```

**Comment by Ostheer** [comment]
Yes! It works now :) Thanks!
